<a href="https://colab.research.google.com/github/MrDegglan/9785-crypto-ml/blob/Raouf-Younes/Init_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install cryptocmd


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


tabular vs multidimensional

pandas used for tabular data, statistics 

numpy used for multidimentional like images

In [ ]:
# Library for crypto currency prediction
from cryptocmd import CmcScraper

# Dependency for pandas, provides arrays, < 50K
import numpy as np

# adds support for DataFrames, > 500K
import pandas as pd

# MinMaxScalar normalises numeric data between 0 and 1 for the purpose of ML training
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

# Used for making a train and test split
from sklearn.model_selection import train_test_split


In [ ]:
# Data download
# ==============================================================================

# Scraper is initialized, symbol, start and end of download are included
scraper = CmcScraper('BTC', '28-04-2013', '24-08-2022')

# Transform collected data into a dataframe
data = scraper.get_dataframe()
data['date'] = pd.to_datetime(data['Date'], format='%Y-%m-%d %H:%M:%S').astype(int) / 10**9

data.sort_values(by='Date', ascending=True, inplace=True)

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
  display(data.tail(5))
  print(len(data))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: casting datetime64[ns] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
  if __name__ == '__main__':


Date          Open          High           Low         Close  \
4 2022-08-20  20872.842174  21350.806299  20856.731336  21166.060396   
3 2022-08-21  21160.392783  21668.845908  21103.196808  21534.121231   
2 2022-08-22  21531.463849  21531.463849  20939.184173  21398.908350   
1 2022-08-23  21401.045670  21646.203762  20955.138156  21528.087372   
0 2022-08-24  21526.455593  21783.075723  21195.006695  21395.020071   

         Volume    Market Cap          date  
4  2.759567e+10  4.048481e+11  1.660954e+09  
3  2.310231e+10  4.119067e+11  1.661040e+09  
2  3.166650e+10  4.093401e+11  1.661126e+09  
1  3.187828e+10  4.118332e+11  1.661213e+09  
0  3.196225e+10  4.093085e+11  1.661299e+09

3406


In [ ]:
pd.to_datetime(['2022-08-20'], format='%Y-%m-%d %H:%M:%S').astype(int) / 10**9

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: casting datetime64[ns] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
  """Entry point for launching an IPython kernel.


Float64Index([1660953600.0], dtype='float64')

In [ ]:
# Data preparation
# ==============================================================================
model_data_y = data.loc[:, ['Open', 'Close', 'High', 'Low']]

model_data_x = data['Close']


# Check N/A
print(model_data_y.isna().sum())
display(model_data_y.tail(5))

print(model_data_x.isna().sum())
display(model_data_x.tail(5))

Open     0
Close    0
High     0
Low      0
dtype: int64


Open         Close          High           Low
4  20872.842174  21166.060396  21350.806299  20856.731336
3  21160.392783  21534.121231  21668.845908  21103.196808
2  21531.463849  21398.908350  21531.463849  20939.184173
1  21401.045670  21528.087372  21646.203762  20955.138156
0  21526.455593  21395.020071  21783.075723  21195.006695

0


4    21166.060396
3    21534.121231
2    21398.908350
1    21528.087372
0    21395.020071
Name: Close, dtype: float64

In [ ]:
scaler_y = MinMaxScaler(feature_range=(0,1))
normalised_data_y = scaler_y.fit_transform(model_data_y)
display(normalised_data_y[:5])

array([[0.00098983, 0.00097453, 0.00089382, 0.00100388],
       [0.00097715, 0.00112757, 0.00106129, 0.00103253],
       [0.00111876, 0.00104549, 0.00105317, 0.00103329],
       [0.00104466, 0.00071941, 0.00095072, 0.00063625],
       [0.00070946, 0.00054489, 0.00074276, 0.00040346]])

In [ ]:
normalised_data_y.shape

(3406, 4)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(model_data_x,normalised_data_y,test_size=0.10,step)

SyntaxError: ignored

In [ ]:
print(x_train)
print(len(x_train))
print("___________________")
print(y_train)
print(len(y_train))

1871    1.499645e+09
1226    1.555373e+09
208     1.643328e+09
3272    1.378598e+09
1939    1.493770e+09
            ...     
694     1.601338e+09
1486    1.532909e+09
1884    1.498522e+09
1920    1.495411e+09
780     1.593907e+09
Name: date, Length: 3065, dtype: float64
3065
___________________
[[0.03640635 0.03413605 0.03583783 0.03401269]
 [0.07406612 0.07655187 0.07515651 0.07524019]
 [0.54918885 0.55876736 0.55123744 0.5450463 ]
 ...
 [0.03571282 0.03680115 0.03606034 0.03419153]
 [0.02926273 0.03118546 0.03244323 0.02943978]
 [0.13422378 0.13341815 0.1322508  0.13437809]]
3065


In [ ]:
print(x_test)
print(len(x_test))
print("___________________")
print(y_test)
print(len(y_test))

588     1.610496e+09
785     1.593475e+09
1111    1.565309e+09
3068    1.396224e+09
1921    1.495325e+09
            ...     
554     1.613434e+09
1740    1.510963e+09
877     1.585526e+09
212     1.642982e+09
737     1.597622e+09
Name: date, Length: 341, dtype: float64
341
___________________
[[0.5015708  0.55183425 0.54610149 0.4903625 ]
 [0.13510536 0.13436707 0.1330607  0.13600396]
 [0.17612252 0.17473756 0.17311919 0.17558546]
 ...
 [0.086795   0.09424536 0.09375869 0.08802795]
 [0.53655257 0.54202616 0.5409725  0.49940084]
 [0.17526581 0.18053718 0.17877442 0.1770474 ]]
341


In [ ]:
# Importing Tensorflow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import LSTM

In [ ]:
model=Sequential()
model.add(LSTM(50,return_sequences=True,input_shape=(1,1)))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(4))
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
x_train_shape = x_train.values.reshape(-1,1)
y_train_shape = y_train.reshape(-1,4)
print((x_train_shape.shape))
print((y_train_shape.shape))

x_test_shape = x_test.values.reshape(-1,1)
y_test_shape = y_test.reshape(-1,4)
print(x_test_shape.shape)
print(y_test_shape.shape)
print(x_test_shape)

(3065, 1)
(3065, 4)
(341, 1)
(341, 4)
[[1.6104960e+09]
 [1.5934752e+09]
 [1.5653088e+09]
 [1.3962240e+09]
 [1.4953248e+09]
 [1.4163552e+09]
 [1.5793056e+09]
 [1.5857856e+09]
 [1.4119488e+09]
 [1.4018400e+09]
 [1.6304544e+09]
 [1.3788576e+09]
 [1.6014240e+09]
 [1.5505344e+09]
 [1.6292448e+09]
 [1.4118624e+09]
 [1.5416352e+09]
 [1.4863392e+09]
 [1.4625792e+09]
 [1.4434848e+09]
 [1.4100480e+09]
 [1.3959648e+09]
 [1.6142976e+09]
 [1.4494464e+09]
 [1.5223680e+09]
 [1.6007328e+09]
 [1.5647904e+09]
 [1.5166656e+09]
 [1.5015456e+09]
 [1.5064704e+09]
 [1.5337728e+09]
 [1.5775776e+09]
 [1.6337376e+09]
 [1.5081120e+09]
 [1.5247872e+09]
 [1.6412544e+09]
 [1.3918176e+09]
 [1.6236288e+09]
 [1.4300928e+09]
 [1.5675552e+09]
 [1.3786848e+09]
 [1.5203808e+09]
 [1.6482528e+09]
 [1.5002496e+09]
 [1.4549760e+09]
 [1.4133312e+09]
 [1.4637024e+09]
 [1.6380576e+09]
 [1.6149888e+09]
 [1.5992640e+09]
 [1.4015808e+09]
 [1.4990400e+09]
 [1.4301792e+09]
 [1.4603328e+09]
 [1.6315776e+09]
 [1.6473024e+09]
 [1.421798

In [ ]:
model.fit(x_train_shape, y_train_shape,validation_data=(x_test_shape,y_test_shape),epochs=10,batch_size=64,verbose=1)


Epoch 1/10
48/48 [==============================] - 3s 17ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 2/10
48/48 [==============================] - 1s 17ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 3/10
48/48 [==============================] - 1s 10ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 4/10
48/48 [==============================] - 1s 17ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 5/10
48/48 [==============================] - 1s 17ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 6/10
48/48 [==============================] - 1s 17ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 7/10
48/48 [==============================] - 1s 17ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 8/10
48/48 [==============================] - 1s 17ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 9/10
48/48 [==============================] - 1s 17ms/step - loss: 0.0546 - val_loss: 0.0567
Epoch 10/10
48/48 [==============================] - 1s 17ms/step - loss: 0.0546 - val_loss: 0.0567


In [ ]:
# 	2022-08-24 00:00:00	21526.455593085484	21783.07572274634	21195.006694910768	21395.02007149252	31962253368.02	409308514098.09	1661299200.0
sample_num = 5
x = x_train[sample_num].reshape(-1,1)
print(x.shape)
print(model.predict(x))
print(y_train[sample_num])

(1, 1)
[[0.15931763 0.15918918 0.16034676 0.15739986]]
[0.00253922 0.00247114 0.00240941 0.00255182]


In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))
ann.add(tf.keras.layers.Dense(units=4, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 10)

Epoch 1/10
96/96 [==============================] - 0s 929us/step - loss: 0.6405 - accuracy: 0.2591
Epoch 2/10
96/96 [==============================] - 0s 1ms/step - loss: 0.5480 - accuracy: 0.2591
Epoch 3/10
96/96 [==============================] - 0s 991us/step - loss: 0.4970 - accuracy: 0.2591
Epoch 4/10
96/96 [==============================] - 0s 1ms/step - loss: 0.4688 - accuracy: 0.2591
Epoch 5/10
96/96 [==============================] - 0s 1ms/step - loss: 0.4535 - accuracy: 0.2591
Epoch 6/10
96/96 [==============================] - 0s 1ms/step - loss: 0.4454 - accuracy: 0.2591
Epoch 7/10
96/96 [==============================] - 0s 1ms/step - loss: 0.4411 - accuracy: 0.2591
Epoch 8/10
96/96 [==============================] - 0s 985us/step - loss: 0.4390 - accuracy: 0.2591
Epoch 9/10
96/96 [==============================] - 0s 943us/step - loss: 0.4378 - accuracy: 0.2591
Epoch 10/10
96/96 [==============================] - 0s 977us/step - loss: 0.4373 - accuracy: 0.2591


In [ ]:
# 	2022-08-24 00:00:00	21526.455593085484	21783.07572274634	21195.006694910768	21395.02007149252	31962253368.02	409308514098.09	1661299200.0
sample_num = 8
x = x_train[sample_num].reshape(-1,1)
print(x.shape)
print(ann.predict(x))
print(y_train[sample_num])

(1, 1)
[[0.17632866 0.15786576 0.15833208 0.15465027]]
[0.00408758 0.00417899 0.0041737  0.00412019]


In [ ]:
x_test

588     1.610496e+09
785     1.593475e+09
1111    1.565309e+09
3068    1.396224e+09
1921    1.495325e+09
            ...     
554     1.613434e+09
1740    1.510963e+09
877     1.585526e+09
212     1.642982e+09
737     1.597622e+09
Name: date, Length: 341, dtype: float64

In [ ]:
x_train

1871    1.499645e+09
1226    1.555373e+09
208     1.643328e+09
3272    1.378598e+09
1939    1.493770e+09
            ...     
694     1.601338e+09
1486    1.532909e+09
1884    1.498522e+09
1920    1.495411e+09
780     1.593907e+09
Name: date, Length: 3065, dtype: float64